font:
  normal:
    family: JetBrainsMono NF
    style: Regular

  bold:
    family: JetBrainsMono NF
    style: Bold

  italic:
    family: JetBrainsMono NF
    style: Italic

  bold_italic:
    family: JetBrainsMono NF
    style: Bold Italic

  size: 11
shell:
  program: /usr/bin/tmux
env:
  TERM: xterm-256color
import:
  - ~/.config/alacritty/catppuccin-mocha.yml

